name: tree-sitter-jinja2

on: [pull_request]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # commenting out windows and mac for now
        # os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2016, windows-2019]
        os: [ubuntu-18.04, ubuntu-20.04]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install LOG=true
      - name: Build tree-sitter
        run: make build LOG=true
      - name: Test tree-sitter
        run: make test LOG=true
      - name: Build bindings
        run: make bindings LOG=true
      - name: Cache wheel for distribution
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/*.whl
          retention-days: 5

  publish:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch wheels from cache
        uses: actions/download-artifact@v2
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/